### ISSUE TITLE
Week 2 - Classy Functions

### ISSUE THREAD

**Issue by PranaviInukurti** [PranaviInukurti/Pranavinukurti.github.io#4]
Individual GitHub pages (Grader - Rebecca): /5 points
Team Score: /2
Individual Score: /3
Github Page: https://pranaviinukurti.github.io/Pranavinukurti.github.io/ 
- [x] GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of  [TT2 (Links to an external site.)](https://github.com/nighthawkcoders/nighthawk_csp/wiki/Tri-3-TT2-Python-Classes) for details)
- [x] Organize files, directories and menus for the first 3 weeks. 
- [x] Write Factorial function using classes, providing implementation of call.
- [x] Select your own Math function. Write it in Imperative and OOP form. 
- [ ] Extra Credit.  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.

**Comment by rebecca-123** [comment]
Individual Score: 2.75/3
- Everything works on IntelliJ but not Repl
Team Score: 2/2

Total: 4.75/5
