### ISSUE TITLE
Algorithmic Final

### ISSUE THREAD

**Issue by PranaviInukurti** [PranaviInukurti/Pranavinukurti.github.io#5]
**Total Score: 9.75/10 (Crossover Grader: Gigi)**
**Score for Twitter Video: 9.9/10**
- Amazing understanding and explanation of the code
- Working runtime and good organization in both GitHub page and code
- Showed enhancement of Crossover partner's project
- Didn't show much about his own individual GitHub page

**Individual Coding:**

- [x] [GitHub Pages showing key learnings and challenges conquered from Tech Talks](https://pranaviinukurti.github.io/Pranavinukurti.github.io/)
- [x] GitHub commits you have made, show GitHub insights into your code commits.
- [x] [Show Code running on Replit as well as IntelliJ](https://replit.com/join/gfnssykgrd-pranaviinukurti)
- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [x] List and Loops: show runtime, code organization, code and comments
- [x] Class review and understanding: show runtime, code organization, code and comments

**Crossover Contribution**

- [x] [Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo](https://github.com/Rebecca-123/rebecca-tri-3/commits/gh-pages)
- [x] [Show anything you have done to enhance what you have learned from Python code](https://replit.com/@rebluecs/CSP#main.py)
- [x] [Link to Rebecca's GitHub Page](https://rebecca-123.github.io/rebecca-tri-3/)

Overview 

- [x] [2 minute video](https://youtu.be/54APJhbV85c)
- [x] Make sure you cover everything, but create your own order and optimize time
- [x] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.
- [x] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.

**Comment by gigiguan** [comment]
**Peer Review Total Grade: 9.75/10**
Individual Coding: 
- [ ]  [GitHub Pages showing key learnings and challenges conquered from Tech Talks] (https://pranaviinukurti.github.io/Pranavinukurti.github.io/): _Has answers to github page actions and replit contains all required hacks but did not update code snippets page on github pages. **-.25**_
- [ ]  GitHub commits you have made, show GitHub insights into your code commits.: _added 1139 lines of code; Shows great commitment throughout the weeks_
- [ ]  [Show Code running on Replit as well as IntelliJ](https://replit.com/join/gfnssykgrd-pranaviinukurti): _Has code running on intellij as well_
- [ ]  Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments - _Yes_
- [ ]  List and Loops: show runtime, code organization, code and comments - _Yes_
- [ ]  Class review and understanding: show runtime, code organization, code and comments - _Has classes FIndGCD and Factorial_

Crossover Contribution

- [ ]  [Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo](https://github.com/Rebecca-123/rebecca-tri-3/commits/gh-pages): _She added colored number, matrix, swap, and factoring functions to Rebecca's project. She also added a timebox with working links and added a code snippets page on her navbar._
- [ ]  [Show anything you have done to enhance what you have learned from Python code](https://replit.com/@rebluecs/CSP#main.py)
- [ ]  [Link to Rebecca's GitHub Page](https://rebecca-123.github.io/rebecca-tri-3/)


Overview
- [ ] [2 minute video](https://youtu.be/54APJhbV85c): _Video is under 2 minutes_
- [ ]  Make sure you cover everything, but create your own order and optimize time
- [ ]  Use Voice or Captions. Try not to wiggle mouse a lot or over scroll. Make sure you have a clear plan before you start.: _Video showed clear effort and preplanning._
- [ ]  Perform video in small parts 15-30 seconds and finish a key subject. Then put the final Video together with Video editing or Youtube playlists.
