### ISSUE TITLE
Accounts and Logins

### ISSUE THREAD

**Issue by PranaviInukurti** [PranaviInukurti/Pranavinukurti.github.io#6]
**Individual: /2**
[Create Task](https://pranaviinukurti.github.io/Pranavinukurti.github.io/create)
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij

**Pair: /3**
[Accounts and Logins Challenges](https://github.com/gigiguan/nighthawk_csp)

- [x] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [x] Hack 1: Add Phone Number to Sign Up / Authorization screen
- [x] Hack 2: Add logout to CRUD screen
- [x] Hack 3: Add login_required to another portion of the project

**Comment by rebecca-123** [comment]
Grader: Rebecca Su
Individual: 2/2
Pair: 3/3
