### ISSUE TITLE
Proctored MCQ 1 : Quiz1 and Quiz2 Scores

### ISSUE THREAD

**Issue by PranaviInukurti** [PranaviInukurti/Pranavinukurti.github.io#7]
### AP Testers
**GH Indi Page and Review Ticket for following...**

- [x] Start review ticket with [study plan](https://github.com/PranaviInukurti/Pranavinukurti.github.io/issues/8) and study reflection for week, due EOD Monday 4/18
- [x] Finals-Quiz1 42/50 and [corrections](https://pranaviinukurti.github.io/Pranavinukurti.github.io/quiz)
- [x] Finals-Quiz2 35/50 and [reflections](https://pranaviinukurti.github.io/Pranavinukurti.github.io/quiz)
- [x] [Create Task](https://pranaviinukurti.github.io/Pranavinukurti.github.io/create) code/runtime and 1 min video are [reviewed by another person](https://github.com/PranaviInukurti/Pranavinukurti.github.io/issues/6), you may request Teacher review as time permits

**Comment by ghost** [comment]
5/5, everything is present and the test corrections are thorough.
